name: Jacoco Coverage

on:
  workflow_call:
    inputs:
      java_version:
        required: false
        type: string
        default: 17
        description: "The Java releases to build the software with (i.e. 11)."
      maven_target:
        required: false
        type: string
        default: test
        description: "The Maven target to build, defaults to 'test'."
      artifact_name:
        required: true
        type: string
        description: "The artifact name of the coverage report to upload"
      artifact_path:
        required: true
        type: string
        description: "The path of the artifact of the coverage report to upload"
      jacoco_csv_path:
        required: true
        type: string
        description: "The path of the jacoco CSV file in the project"
      committer_email:
        required: true
        type: string
        description: "EMail address of the commiter"
      committer_user:
        required: true
        type: string
        description: "User name of the commiter"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK ${{ inputs.java_version }}
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ inputs.java_version }}

    - name: Build with Maven
      run: mvn -B ${{ inputs.maven_target }}

    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2.0.1
      with:
        jacoco-csv-file: ${{ inputs.jacoco_csv_path }}

    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
    - name: Commit the badge (if it changed)
      run: |
        echo "committer_user:  ${{ inputs.committer_user }}"
        echo "committer_email: ${{ inputs.committer_email }}"
        if [[ `git status --porcelain` ]]; then
          git config --global user.name "${{ inputs.committer_user }}"
          git config --global user.email "${{ inputs.committer_email }}"
          git add -A
          git commit -m "Autogenerated JaCoCo coverage badge"
          git push
        fi
    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.artifact_path }}
