---
name: JPackage

on:
  workflow_call:
    inputs:
      java_version:
        required: false
        type: string
        default: '21'
        description: "Stringified JSON object listing the Java releases to build the software with (i.e. 11)."
      maven_target:
        required: false
        type: string
        default: package
        description: "The Maven target to build, defaults to 'package'."
      artifact_name:
        required: false
        type: string
        description: "The artifact name to upload, defaults to 'jpackage'"
        default: "jpackage"
      jpackage_input:
        required: true
        type: string
        description: "The directory to change to. Matches the jpackage option --input."
      jpackage_name:
        required: true
        type: string
        description: "The name of the package. Usually the application name. Matches the jpackage option --name."
      jpackage_jarfile:
        required: true
        type: string
        description: "Path of the JAR file with the main class and method."
      jpackage_license:
        required: true
        type: string
        description: "Path of the LICENSE file."
      jpackage_vendor:
        required: true
        type: string
        description: "Vendor name, matches the --vendor flag of jpackage."
      jpackage_copyright:
        required: true
        type: string
        description: "Copyright matches the --copyright flag of jpackage."
      jpackage_description:
        required: true
        type: string
        description: "Description of the package. Matches the --description flag of jpackage."
      jpackage_mainclass:
        required: true
        type: string
        description: "Name of the main class. Matches the --main-class flag of jpackage."
      jpackage_linux_deb_maintainer:
        required: true
        type: string
        description: "Matches the --linux-deb-maintainer flag of jpackage."
      jpackage_linux_deb_app_category:
        required: false
        type: string
        description: "Matches the --linux-app-category flag of jpackage. See sections here: https://packages.debian.org/unstable/"
        default: utils
      jpackage_linux_rpm_app_category:
        required: false
        type: string
        description: "Matches the --linux-app-category flag of jpackage."
        default: utilities
      jpackage_linux_install_dir:
        required: false
        type: string
        description: "Matches the --install-dir flag of jpackage."
        default: /usr
      jpackage_macos_install_dir:
        required: false
        type: string
        description: "Matches the --install-dir flag of jpackage."
        default: /Applications
      jpackage_win_upgrade_uuid:
        required: true
        type: string
        description: "Matches the --win-upgrade-uuid flag of jpackage."
      jpackage_additional_options:
        required: false
        type: string
        description: "Additional options to pass to jpackage."
        default: ""

env:
  JPACKAGE_COMMON_OPTS: |
            --name "${{ inputs.jpackage_name }}" \
            --copyright "${{ inputs.jpackage_copyright }}" \
            --vendor "${{ inputs.jpackage_vendor }}" \
            --description "${{ inputs.jpackage_description }}" \
            --main-class "${{ inputs.jpackage_mainclass }}" \
            --dest jpackage-app \
            --verbose \
            ${{ inputs.jpackage_additional_options }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ inputs.java_version }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Extract current maven version
        run: echo "version=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
        id: version
        shell: bash


      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: "**/target/*"

  ###
  ### Debian Linux
  ### Oracle Linux
  ###
  jpackage_linux:
    needs: build
    outputs:
      packagename: ${{ steps.packagename.outputs.packagename }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            container: debian:bullseye-slim
            jpkg_type: deb
            style: debian
          - os: ubuntu-latest
            container: oraclelinux:8.5
            jpkg_type: rpm
            style: redhat
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    env:
      PACKAGE_VERSION: ${{ needs.build.outputs.version }}
      CLASSPATH_SEPARATOR: ":"
      PATH_SEPARATOR: "/"
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: Setup Debian container
        run: |
          echo "List of current dir:"
          ls -alR
          echo "Debian version:"
          cat /etc/debian_version
          apt-get update
          apt-get install -y --no-install-recommends curl openssh-client git fakeroot curl binutils
        if: matrix.style == 'debian'
      - name: Setup OracleLinux container
        run: |
          echo "List of current dir:"
          ls -alR
          yum install --assumeyes rpm-build git openssh-clients
        if: matrix.style == 'redhat'
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ inputs.java_version }}
      - name: Build package
        run: |
          APP_CATEGORY="${{ inputs.jpackage_linux_deb_app_category }}"
          if test "${{ matrix.style }}" = "redhat"; then
            PACKAGE_VERSION=$(echo ${PACKAGE_VERSION} | cut -d"-" -f1)
            APP_CATEGORY="${{ inputs.jpackage_linux_rpm_app_category }}"
            echo "Fixing RPM version to ${PACKAGE_VERSION}"
          fi
          jpackage \
            --main-jar ${{ inputs.jpackage_jarfile }} \
            --type "${{ matrix.jpkg_type }}" \
            --app-version "${PACKAGE_VERSION}" \
            --input "${{ inputs.jpackage_input }}" \
            --license-file "${{ inputs.jpackage_license }}" \
            --linux-deb-maintainer "${{ inputs.jpackage_linux_deb_maintainer }}" \
            --linux-app-category "$APP_CATEGORY" \
            --install-dir "${{ inputs.jpackage_linux_install_dir }}" \
            ${{ env.JPACKAGE_COMMON_OPTS }}
      - name: Extract package name
        run: echo "packagename=$(ls)" >> $GITHUB_OUTPUT
        working-directory: jpackage-app
        id: packagename
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.jpkg_type }}
          path: jpackage-app/${{ steps.packagename.outputs.packagename }}

  ###
  ### MacOS
  ###
  jpackage_macos:
    needs: build
    outputs:
      packagename: ${{ steps.packagename.outputs.packagename }}
    strategy:
      matrix:
        include:
          - jpkg_type: dmg
          - jpkg_type: pkg
    runs-on: macos-latest
    env:
      PACKAGE_VERSION: ${{ needs.build.outputs.version }}
      CLASSPATH_SEPARATOR: ":"
      PATH_SEPARATOR: "/"
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ inputs.java_version }}
      - name: Build package
        run: |
          PACKAGE_VERSION=$(echo ${PACKAGE_VERSION} | cut -d"-" -f1)
          jpackage \
            --main-jar "${{ inputs.jpackage_jarfile }}" \
            --type "${{ matrix.jpkg_type }}" \
            --app-version "${PACKAGE_VERSION}" \
            --input "${{ inputs.jpackage_input }}" \
            --license-file "${{ inputs.jpackage_license }}" \
            --install-dir "${{ inputs.jpackage_macos_install_dir }}" \
            ${{ env.JPACKAGE_COMMON_OPTS }}
      - name: Extract package name
        run: echo "packagename=$(ls)" >> $GITHUB_OUTPUT
        working-directory: jpackage-app
        id: packagename
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.jpkg_type }}
          path: jpackage-app/${{ steps.packagename.outputs.packagename }}


  ###
  ### Windows
  ###
  jpackage_windows:
    needs: build
    outputs:
      packagename: ${{ steps.packagename.outputs.packagename }}
    strategy:
      matrix:
        include:
          - jpkg_type: exe
          - jpkg_type: msi
    runs-on: windows-latest
    env:
      PACKAGE_VERSION: ${{ needs.build.outputs.version }}
      CLASSPATH_SEPARATOR: ";"
      PATH_SEPARATOR: "\\"
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ inputs.java_version }}
      - name: Build package
        run: |
          PACKAGE_VERSION=$(echo ${PACKAGE_VERSION} | cut -d"-" -f1)
          jpackage \
            --main-jar "${{ inputs.jpackage_jarfile }}" \
            --type "${{ matrix.jpkg_type }}" \
            --app-version "${PACKAGE_VERSION}" \
            --input "${{ inputs.jpackage_input }}" \
            --license-file "${{ inputs.jpackage_license }}" \
            --win-console \
            --win-upgrade-uuid "${{ inputs.jpackage_win_upgrade_uuid }}" \
            ${{ env.JPACKAGE_COMMON_OPTS }}
        shell: bash
      - name: Extract package name
        run: echo "packagename=$(ls)" >> $GITHUB_OUTPUT
        working-directory: jpackage-app
        id: packagename
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.jpkg_type }}
          path: jpackage-app/${{ steps.packagename.outputs.packagename }}

  ###
  ### Linux Build via QEMU
  ###
  jpackage_linux_multiarch:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: arm64
            platform: linux/arm64
            distro: debian:bullseye-slim
            jpkg_type: deb
            adoptium_arch: aarch64
          - arch: ppc64le
            platform: linux/ppc64le
            distro: ubuntu:20.04
            jpkg_type: deb
            adoptium_arch: ppc64le
          - arch: s390x
            platform: linux/s390x
            distro: ubuntu:20.04
            jpkg_type: deb
            adoptium_arch: s390x

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Build ${{ matrix.arch }} package in Docker
        run: |
          docker run --rm --platform=${{ matrix.platform }} \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            ${{ matrix.distro }} /bin/bash -c "
              set -e
              apt-get update && \
              apt-get install -y curl unzip binutils fakeroot tar gzip ca-certificates && \
              jdk_version='${{ inputs.java_version }}' && \
              curl -L -o jdk.tar.gz \"https://api.adoptium.net/v3/binary/latest/\$jdk_version/ga/linux/${{ matrix.adoptium_arch }}/jdk/hotspot/normal/adoptium\" && \
              mkdir -p /opt/java && \
              tar -xzf jdk.tar.gz -C /opt/java --strip-components=1 && \
              export PATH=\"/opt/java/bin:\$PATH\" && \
              java -version && \
              mkdir -p jpackage-app && \
              jpackage \
                --type ${{ matrix.jpkg_type }} \
                --input '${{ inputs.jpackage_input }}' \
                --main-jar '${{ inputs.jpackage_jarfile }}' \
                --name '${{ inputs.jpackage_name }}' \
                --app-version '${{ needs.build.outputs.version }}' \
                --license-file '${{ inputs.jpackage_license }}' \
                --linux-deb-maintainer '${{ inputs.jpackage_linux_deb_maintainer }}' \
                --linux-app-category '${{ inputs.jpackage_linux_deb_app_category }}' \
                --install-dir '${{ inputs.jpackage_linux_install_dir }}' \
                --main-class '${{ inputs.jpackage_mainclass }}' \
                --description '${{ inputs.jpackage_description }}' \
                --vendor '${{ inputs.jpackage_vendor }}' \
                --copyright '${{ inputs.jpackage_copyright }}' \
                --dest jpackage-app \
                --verbose \
                ${{ inputs.jpackage_additional_options }}
            "

      - uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.arch }}
          path: jpackage-app/

  merge_packages:
    needs:
      - build
      - jpackage_linux
      - jpackage_linux_multiarch
      - jpackage_macos
      - jpackage_windows
    runs-on: ubuntu-latest
    steps:
      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          path: packages
          pattern: packages-*
          merge-multiple: true
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: packages
