---
name: Spotbugs with Maven

on:
  workflow_call:
    inputs:
      java_version:
        required: false
        type: string
        default: '21'
        description: "Stringified JSON object listing the Java releases to build the software with (i.e. 11)."
      artifact_name:
        required: true
        type: string
        description: "The artifact name to upload"

jobs:
  spotbugs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: ${{fromJson(inputs.java_version)}}
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:

    - uses: actions/checkout@v3

    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java_version }}
        distribution: temurin

    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run spotbugs with Maven
      run: mvn install && mvn com.github.spotbugs:spotbugs-maven-plugin:4.9.3.0:spotbugs -Dspotbugs.xmlOutput=true -Dspotbugs.htmlOutput=true

    - name: Collect spotbugs output
      run: echo "path=$(find . -ipath '*spotbugs.*')" >> "$GITHUB_OUTPUT"

    - name: Found paths
      run: "echo ${{ steps.spotbugs.outputs.path }}"

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}_${{ matrix.java_version }}
        path: ${{ steps.spotbugs.outputs.path }}
