---
name: Spotbugs with Maven

on:
  workflow_call:
    inputs:
      java_version:
        required: false
        type: string
        default: '21'
        description: "Java release to build the software with (i.e. 11)."
      artifact_name:
        required: true
        type: string
        description: "The artifact name to upload"

jobs:
  spotbugs:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:

    - uses: actions/checkout@v3

    - name: Set up JDK ${{ inputs.java_version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java_version }}
        distribution: temurin

    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Maven Build with Debug
      run: |
        mvn compiler:compile -Dcompiler.debug=true -Dcompiler.debuglevel=lines,vars,source

    - name: Download spotbugs
      run: |
        mkdir /tmp/spotbugs
        wget https://github.com/spotbugs/spotbugs/releases/download/4.9.3/spotbugs-4.9.3.tgz -O- | tar --strip-components=1 -C/tmp/spotbugs -xzvf- 
        wget https://search.maven.org/remotecontent?filepath=com/h3xstream/findsecbugs/findsecbugs-plugin/1.12.0/findsecbugs-plugin-1.12.0.jar -O/tmp/findsecbugs-plugin.jar
        wget https://repo1.maven.org/maven2/com/mebigfatguy/fb-contrib/fb-contrib/7.6.9/fb-contrib-7.6.9.jar -O/tmp/fb-contrib.jar

    - name: Run spotbugs with Plugins
      run: |
        SOURCEPATH=$(find -ipath "**/src/main/java" -printf "%p:")
        /tmp/spotbugs/bin/spotbugs -projectName Project -textui -pluginList "/tmp/findsecbugs-plugin.jar:/tmp/fb-contrib.jar" -sourcepath "${SOURCEPATH}" -html:fancy.xsl=spotbugs.html -xml=spotbugs.xml -low -longBugCodes $(find -ipath **/target/**/*.class)

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: |
          ./spotbugs.xml
          ./spotbugs.html
